LOGIN_REQUIRED = 'Its necessary start session.'
USER_CREATED = 'User created successfully.'
TASK_CREATED = 'Task created successfully.'
LOGOUT = 'Session is closed successfully.'
ERROR_USER_PASSWORD = 'User or password invalid.'
LOGIN_SUCCESS = 'User authenticated successfully'